plugins {
    id("base-conventions")
    id("integration-test-suite")
}

dependencies {
    implementation(projects.api.account)
    implementation(projects.api.db)
    implementation(projects.api.pluginCommons)
    implementation(projects.api.registry)
    implementation(projects.content.interfaces.levelup)
    // The skills whose events the task script listens on.
    implementation(projects.content.skills.agility)
    implementation(projects.content.skills.cooking)
    implementation(projects.content.skills.crafting)
    implementation(projects.content.skills.farming)
    implementation(projects.content.skills.firemaking)
    implementation(projects.content.skills.fishing)
    implementation(projects.content.skills.fletching)
    implementation(projects.content.skills.herblore)
    implementation(projects.content.skills.hunter)
    implementation(projects.content.skills.magic.magicCommons)
    implementation(projects.content.skills.mining)
    implementation(projects.content.skills.prayer)
    implementation(projects.content.skills.smithing)
    implementation(projects.content.skills.thieving)
    implementation(projects.content.skills.woodcutting)
    integrationImplementation(projects.api.hitPlugin)
    integrationImplementation(projects.content.interfaces.levelup)
    integrationImplementation(projects.content.skills.mining)
    integrationImplementation(projects.content.skills.smithing)
    integrationImplementation(projects.api.player)
    integrationImplementation(projects.api.pluginCommons)
    integrationImplementation(projects.api.specials)
}
