package org.rsmod.content.custom.droptables.data

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertSame
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.rsmod.api.testing.GameTestState
import org.rsmod.content.custom.droptables.DropSlot
import org.rsmod.content.custom.droptables.DropTable
import org.rsmod.content.custom.droptables.WeightedTable
import org.rsmod.content.custom.droptables.configs.LumbridgeDropTables
import org.rsmod.game.type.obj.ObjType

/**
 * Guards the tables generated by `tools/drop-tables/generate.py`.
 *
 * `DropTableResourceLoader` deliberately collects bad rows instead of throwing, so that a stale
 * name cannot take a live server down. This is where that leniency is paid for: the error list has
 * to be empty here, which makes a bad import a red build rather than a quiet gap in the game.
 */
class GeneratedDropTablesTest {
    @Test
    fun GameTestState.`every generated row loads`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            val result = loader.load()
            assertTrue(
                result.errors.isEmpty(),
                "Generated drop tables had ${result.errors.size} bad rows. First 10:\n" +
                    result.errors.take(10).joinToString("\n"),
            )
            assertTrue(result.assignments.isNotEmpty(), "No generated drop tables were loaded.")
        }

    @Test
    fun GameTestState.`every weighted table sums to its denominator`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // `WeightedTableBuilder` enforces this for hand-written tables, but the loader builds
            // `WeightedTable` directly, so nothing else checks the generated ones.
            for ((npc, table) in loader.load().assignments) {
                for (weighted in table.tables.flatMap { it.selfAndNested() }) {
                    assertEquals(
                        weighted.denominator,
                        weighted.slots.sumOf(DropSlot::weight),
                        "Weighted table for '${npc.internalName}' does not sum to its denominator.",
                    )
                }
            }
        }

    @Test
    fun GameTestState.`every generated drop resolves to an obj in the cache`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            for ((npc, table) in loader.load().assignments) {
                for (obj in table.allObjs()) {
                    val resolved = cacheTypes.objs[obj]
                    assertTrue(
                        resolved.name.isNotBlank(),
                        "Drop for '${npc.internalName}' has no name: $obj",
                    )
                }
            }
        }

    @Test
    fun GameTestState.`every npc with a generated table can be attacked`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // The loader drops these itself, since a wiki page lists a monster's cutscene and
            // reset forms alongside the real thing. Assert it actually did.
            val unattackable =
                loader.load().assignments.filterNot { (npc, _) ->
                    cacheTypes.npcs[npc].op.any { it.equals("Attack", ignoreCase = true) }
                }
            assertTrue(
                unattackable.isEmpty(),
                "${unattackable.size} generated tables sit on npcs with no Attack op: " +
                    unattackable.take(20).map { it.first.internalName },
            )
        }

    @Test
    fun GameTestState.`hand-written tables win every npc they share`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // The wiki covers the six hand-written tables too, so overlap is expected. What
            // matters is that `DropTableScript`'s precedence rule resolves it the way it claims,
            // rather than the two silently racing. Replay that rule here.
            val handWritten =
                LumbridgeDropTables.assignments.associate { (type, table) ->
                    cacheTypes.npcs[type].id to table
                }
            val generated = loader.load().assignments

            val overlap = generated.filter { it.first.id in handWritten }
            assertTrue(
                overlap.isNotEmpty(),
                "Expected the wiki to cover the hand-written npcs; the precedence rule is " +
                    "untested if it does not.",
            )

            val registered = handWritten.toMutableMap()
            for ((npc, table) in generated) {
                registered.putIfAbsent(npc.id, table)
            }
            for ((id, table) in handWritten) {
                assertSame(
                    table,
                    registered[id],
                    "A generated table displaced the hand-written one for npc id $id.",
                )
            }
        }

    private fun DropTable.allObjs(): List<ObjType> =
        always.map { it.obj } +
            tables.flatMap { table -> table.selfAndNested().flatMap { it.slots.itemObjs() } } +
            tertiary.map { it.drop.obj }

    private fun WeightedTable.selfAndNested(): List<WeightedTable> =
        listOf(this) +
            slots.filterIsInstance<DropSlot.Nested>().flatMap { it.table.selfAndNested() }

    private fun List<DropSlot>.itemObjs(): List<ObjType> =
        filterIsInstance<DropSlot.Item>().map { it.drop.obj }
}
