package org.rsmod.content.custom.droptables.data

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertSame
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.rsmod.api.testing.GameTestState
import org.rsmod.content.custom.droptables.DropSlot
import org.rsmod.content.custom.droptables.DropTable
import org.rsmod.content.custom.droptables.WeightedTable
import org.rsmod.content.custom.droptables.configs.LumbridgeDropTables
import org.rsmod.game.type.obj.ObjType

/**
 * Guards the tables generated by `tools/drop-tables/generate.py`.
 *
 * `DropTableResourceLoader` deliberately collects bad rows instead of throwing, so that a stale
 * name cannot take a live server down. This is where that leniency is paid for: the error list has
 * to be empty here, which makes a bad import a red build rather than a quiet gap in the game.
 */
class GeneratedDropTablesTest {
    @Test
    fun GameTestState.`every generated row loads`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            val result = loader.load()
            assertTrue(
                result.errors.isEmpty(),
                "Generated drop tables had ${result.errors.size} bad rows. First 10:\n" +
                    result.errors.take(10).joinToString("\n"),
            )
            assertTrue(result.assignments.isNotEmpty(), "No generated drop tables were loaded.")
        }

    @Test
    fun GameTestState.`every weighted table sums to its denominator`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // `WeightedTableBuilder` enforces this for hand-written tables, but the loader builds
            // `WeightedTable` directly, so nothing else checks the generated ones.
            for ((npc, table) in loader.load().assignments) {
                for (weighted in table.tables.flatMap { it.selfAndNested() }) {
                    assertEquals(
                        weighted.denominator,
                        weighted.slots.sumOf(DropSlot::weight),
                        "Weighted table for '${npc.internalName}' does not sum to its denominator.",
                    )
                }
            }
        }

    @Test
    fun GameTestState.`every generated drop resolves to an obj in the cache`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            for ((npc, table) in loader.load().assignments) {
                for (obj in table.allObjs()) {
                    val resolved = cacheTypes.objs[obj]
                    assertTrue(
                        resolved.name.isNotBlank(),
                        "Drop for '${npc.internalName}' has no name: $obj",
                    )
                }
            }
        }

    @Test
    fun GameTestState.`every npc with a generated table can be attacked`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // The loader drops these itself, since a wiki page lists a monster's cutscene and
            // reset forms alongside the real thing. Assert it actually did.
            val unattackable =
                loader.load().assignments.filterNot { (npc, _) ->
                    cacheTypes.npcs[npc].op.any { it.equals("Attack", ignoreCase = true) }
                }
            assertTrue(
                unattackable.isEmpty(),
                "${unattackable.size} generated tables sit on npcs with no Attack op: " +
                    unattackable.take(20).map { it.first.internalName },
            )
        }

    @Test
    fun GameTestState.`hand-written tables win every npc they share`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // The wiki covers the six hand-written tables too, so overlap is expected. What
            // matters is that `DropTableScript`'s precedence rule resolves it the way it claims,
            // rather than the two silently racing. Replay that rule here.
            val handWritten =
                LumbridgeDropTables.assignments.associate { (type, table) ->
                    cacheTypes.npcs[type].id to table
                }
            val generated = loader.load().assignments

            val overlap = generated.filter { it.first.id in handWritten }
            assertTrue(
                overlap.isNotEmpty(),
                "Expected the wiki to cover the hand-written npcs; the precedence rule is " +
                    "untested if it does not.",
            )

            val registered = handWritten.toMutableMap()
            for ((npc, table) in generated) {
                registered.putIfAbsent(npc.id, table)
            }
            for ((id, table) in handWritten) {
                assertSame(
                    table,
                    registered[id],
                    "A generated table displaced the hand-written one for npc id $id.",
                )
            }
        }

    @Test
    fun GameTestState.`clue scrolls drop as keys and no other trail item drops`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // `generate.py` rewrites each clue scroll as the key of its tier (`CLUE_KEYS`) and
            // skips every other trail item: nothing implements trails, and the step keys the wiki
            // lists as "Always" only drop while on that clue step.
            for ((npc, table) in loader.load().assignments) {
                val names = table.allObjs().map { cacheTypes.objs[it].internalName }
                val stray = names.filter { it?.startsWith("trail_") == true && it !in CLUE_KEYS }
                assertTrue(stray.isEmpty(), "'${npc.internalName}' drops trail items $stray.")
                val always = table.always.map { cacheTypes.objs[it.obj].internalName }
                assertTrue(
                    always.none { it in CLUE_KEYS } || npc.internalName in ALWAYS_CLUE_NPCS,
                    "'${npc.internalName}' always drops a clue key: $always",
                )
            }
        }

    @Test
    fun GameTestState.`guards drop a medium key at the medium clue rate`() =
        runInjectedGameTest(DropTableResourceLoader::class) { loader ->
            // `guard1` is the Varrock fountain guard, on the wiki's shared "Guard" page. It used
            // to drop a Key (medium) on every kill.
            val guard = loader.load().assignments.single { it.first.internalName == "guard1" }
            val table = guard.second
            assertTrue(table.always.none { cacheTypes.objs[it.obj].internalName in CLUE_KEYS })
            val key =
                table.tertiary.single {
                    cacheTypes.objs[it.drop.obj].internalName == "trail_clue_medium_riddle001_key"
                }
            assertEquals(128, key.oneIn)
        }

    private fun DropTable.allObjs(): List<ObjType> =
        always.map { it.obj } +
            tables.flatMap { table -> table.selfAndNested().flatMap { it.slots.itemObjs() } } +
            tertiary.map { it.drop.obj }

    private fun WeightedTable.selfAndNested(): List<WeightedTable> =
        listOf(this) +
            slots.filterIsInstance<DropSlot.Nested>().flatMap { it.table.selfAndNested() }

    private fun List<DropSlot>.itemObjs(): List<ObjType> =
        filterIsInstance<DropSlot.Item>().map { it.drop.obj }

    private companion object {
        /** `CLUE_KEYS` in `tools/drop-tables/generate.py`. */
        val CLUE_KEYS =
            setOf(
                "trail_key_beginner",
                "trail_key_easy",
                "trail_clue_medium_riddle001_key",
                "trail_key_hard",
                "trail_elite_riddle_key32",
            )

        /** Npcs whose wiki clue scroll really is "Always", so the key is too: Skotizo. */
        val ALWAYS_CLUE_NPCS = setOf<String?>("cata_boss")
    }
}
