package org.rsmod.content.custom.cityshops.configs

import org.rsmod.api.type.refs.obj.ObjReferences

internal typealias shop_objs = ShopObjs

/**
 * Objs our shops stock that [org.rsmod.api.config.refs.BaseObjs] does not already expose. Anything
 * already in `objs` is used from there instead of redeclared here, which is why some equipment
 * ladders below skip a tier: upstream happens to expose `rune_platelegs` and `rune_platebody`, but
 * none of the other tiers.
 */
object ShopObjs : ObjReferences() {
    // Zeke's Superior Scimitars.
    val bronze_scimitar = find("bronze_scimitar")
    val iron_scimitar = find("iron_scimitar")
    val steel_scimitar = find("steel_scimitar")
    val mithril_scimitar = find("mithril_scimitar")
    val adamant_scimitar = find("adamant_scimitar")
    val rune_scimitar = find("rune_scimitar")

    // Ranael's Super Skirt Store.
    val bronze_plateskirt = find("bronze_plateskirt")
    val iron_plateskirt = find("iron_plateskirt")
    val steel_plateskirt = find("steel_plateskirt")
    val mithril_plateskirt = find("mithril_plateskirt")
    val adamant_plateskirt = find("adamant_plateskirt")
    val rune_plateskirt = find("rune_plateskirt")

    // Louie Legs' Leg Wear.
    val bronze_platelegs = find("bronze_platelegs")
    val iron_platelegs = find("iron_platelegs")
    val steel_platelegs = find("steel_platelegs")
    val mithril_platelegs = find("mithril_platelegs")
    val adamant_platelegs = find("adamant_platelegs")

    // Horvik's Armour Shop.
    val bronze_chainbody = find("bronze_chainbody")
    val iron_chainbody = find("iron_chainbody")
    val steel_chainbody = find("steel_chainbody")
    val mithril_chainbody = find("mithril_chainbody")
    val adamant_chainbody = find("adamant_chainbody")
    val rune_chainbody = find("rune_chainbody")
    val bronze_platebody = find("bronze_platebody")
    val iron_platebody = find("iron_platebody")
    val steel_platebody = find("steel_platebody")
    val mithril_platebody = find("mithril_platebody")
    val adamant_platebody = find("adamant_platebody")
    val leather_armour = find("leather_armour")
    val studded_body = find("studded_body")

    // Dommik's Crafting Store.
    val ring_mould = find("ring_mould")
    val necklace_mould = find("necklace_mould")
    val amulet_mould = find("amulet_mould")
    val needle = find("needle")
    val thread = find("thread")

    // Gem trader.
    val uncut_opal = find("uncut_opal")
    val uncut_jade = find("uncut_jade")
    val uncut_red_topaz = find("uncut_red_topaz")
    val uncut_sapphire = find("uncut_sapphire")
    val uncut_emerald = find("uncut_emerald")
    val uncut_ruby = find("uncut_ruby")
    val uncut_diamond = find("uncut_diamond")

    // Aubury's Rune Shop.
    val body_rune = find("bodyrune")
    val cosmic_rune = find("cosmicrune")

    // Zaff's Superior Staffs.
    val staff = find("plainstaff")
    val magic_staff = find("magic_staff")
    val staff_of_water = find("staff_of_water")
    val staff_of_earth = find("staff_of_earth")
    val staff_of_fire = find("staff_of_fire")
    val battlestaff = find("battlestaff")

    // Lowe's Archery Emporium.
    val iron_arrow = find("iron_arrow")
    val steel_arrow = find("steel_arrow")
    val mithril_arrow = find("mithril_arrow")
    val longbow = find("longbow")
    val oak_shortbow = find("oak_shortbow")
    val oak_longbow = find("oak_longbow")
    val willow_shortbow = find("willow_shortbow")
    val willow_longbow = find("willow_longbow")
    val maple_shortbow = find("maple_shortbow")
    val maple_longbow = find("maple_longbow")
    val yew_shortbow = find("yew_shortbow")
    val yew_longbow = find("yew_longbow")
    val crossbow = find("crossbow")
    val bronze_bolts = find("bolt")

    // Varrock Swordshop.
    val bronze_sword = find("bronze_sword")
    val iron_sword = find("iron_sword")
    val steel_sword = find("steel_sword")
    val mithril_sword = find("mithril_sword")
    val adamant_sword = find("adamant_sword")
    val rune_sword = find("rune_sword")
    val bronze_longsword = find("bronze_longsword")
    val iron_longsword = find("iron_longsword")
    val steel_longsword = find("steel_longsword")
    val mithril_longsword = find("mithril_longsword")
    val adamant_longsword = find("adamant_longsword")
    val rune_longsword = find("rune_longsword")
    val bronze_dagger = find("bronze_dagger")
    val iron_dagger = find("iron_dagger")
    val steel_dagger = find("steel_dagger")
    val mithril_dagger = find("mithril_dagger")
    val adamant_dagger = find("adamant_dagger")
    val rune_dagger = find("rune_dagger")

    // Thessalia's Fine Clothes.
    val pink_skirt = find("pink_skirt")
    val black_skirt = find("black_skirt")
    val blue_skirt = find("blue_skirt")
    val red_cape = find("red_cape")
    val blue_cape = find("blue_cape")
    val yellow_cape = find("yellow_cape")
    val green_cape = find("green_cape")
    val purple_cape = find("purple_cape")
    val orange_cape = find("orange_cape")
    val black_cape = find("black_cape")

    // Added with the Falador, Port Sarim, Champions' Guild, Taverley, Catherby, Yanille,
    // Dwarven Mine, Brimhaven and Edgeville shops. Grouped by nothing but the alphabet: most of
    // these are shared by several shops, so a per-shop grouping would repeat them.
    //
    // Ten of the herblore secondaries are not spelled the way you would guess -- `cactus_potato`
    // is potato cactus, `mortmyremushroom` is mort myre fungus, `huntingbeast_sabreteeth` is
    // kebbit teeth, `amylase` is an amylase crystal, `sote_crystal_dust` is crystal dust. These
    // are the cache's own names; `.data/symbols/obj.sym` is the authority, not the wiki.
    val adamant_2h_sword = find("adamant_2h_sword")
    val adamant_arrowheads = find("adamant_arrowheads")
    val adamant_battleaxe = find("adamant_battleaxe")
    val adamant_full_helm = find("adamant_full_helm")
    val adamant_mace = find("adamant_mace")
    val adamant_med_helm = find("adamant_med_helm")
    val adamant_pickaxe = find("adamant_pickaxe")
    val amulet_of_defence = find("amulet_of_defence")
    val amulet_of_magic = find("amulet_of_magic")
    val amulet_of_power = find("amulet_of_power")
    val amulet_of_strength = find("amulet_of_strength")
    val amylase = find("amylase")
    val ashes = find("ashes")
    val banana = find("banana")
    val big_net = find("big_net")
    val black_2h_sword = find("black_2h_sword")
    val black_battleaxe = find("black_battleaxe")
    val black_chainbody = find("black_chainbody")
    val black_full_helm = find("black_full_helm")
    val black_platelegs = find("black_platelegs")
    val blackwizhat = find("blackwizhat")
    val blue_dragon_scale = find("blue_dragon_scale")
    val bluewizhat = find("bluewizhat")
    val bread = find("bread")
    val bronze_2h_sword = find("bronze_2h_sword")
    val bronze_arrowheads = find("bronze_arrowheads")
    val bronze_battleaxe = find("bronze_battleaxe")
    val bronze_full_helm = find("bronze_full_helm")
    val bronze_kiteshield = find("bronze_kiteshield")
    val bronze_mace = find("bronze_mace")
    val bronze_med_helm = find("bronze_med_helm")
    val bronze_sq_shield = find("bronze_sq_shield")
    val butterfly_jar = find("butterfly_jar")
    val cactus_potato = find("cactus_potato")
    val cheese = find("cheese")
    val chocolate_bar = find("chocolate_bar")
    val chocolate_dust = find("chocolate_dust")
    val coif = find("coif")
    val cooking_apple = find("cooking_apple")
    val crushed_bird_nest = find("crushed_bird_nest")
    val cup_empty = find("cup_empty")
    val desert_goat_horn = find("desert_goat_horn")
    val diamond = find("diamond")
    val diamond_necklace = find("diamond_necklace")
    val diamond_ring = find("diamond_ring")
    val dragon_vambraces = find("dragon_vambraces")
    val dragonhide_chaps = find("dragonhide_chaps")
    val emerald = find("emerald")
    val emerald_necklace = find("emerald_necklace")
    val emerald_ring = find("emerald_ring")
    val eye_of_newt = find("eye_of_newt")
    val feather = find("feather")
    val fishing_bait = find("fishing_bait")
    val fishing_rod = find("fishing_rod")
    val fly_fishing_rod = find("fly_fishing_rod")
    val garlic = find("garlic")
    val gold_necklace = find("gold_necklace")
    val gold_ring = find("gold_ring")
    val harpoon = find("harpoon")
    val holy_symbol_mould = find("holy_symbol_mould")
    val hunting_box_trap = find("hunting_box_trap")
    val hunting_butterfly_net = find("hunting_butterfly_net")
    val hunting_ojibway_bird_snare = find("hunting_ojibway_bird_snare")
    val hunting_teasing_stick = find("hunting_teasing_stick")
    val huntingbeast_sabreteeth = find("huntingbeast_sabreteeth")
    val iron_2h_sword = find("iron_2h_sword")
    val iron_arrowheads = find("iron_arrowheads")
    val iron_full_helm = find("iron_full_helm")
    val iron_kiteshield = find("iron_kiteshield")
    val iron_mace = find("iron_mace")
    val iron_med_helm = find("iron_med_helm")
    val iron_pickaxe = find("iron_pickaxe")
    val iron_sq_shield = find("iron_sq_shield")
    val jangerberries = find("jangerberries")
    val jewl_bracelet_mould = find("jewl_bracelet_mould")
    val limpwurt_root = find("limpwurt_root")
    val lobster_pot = find("lobster_pot")
    val mithril_2h_sword = find("mithril_2h_sword")
    val mithril_arrowheads = find("mithril_arrowheads")
    val mithril_full_helm = find("mithril_full_helm")
    val mithril_mace = find("mithril_mace")
    val mithril_med_helm = find("mithril_med_helm")
    val mithril_pickaxe = find("mithril_pickaxe")
    val mithril_sq_shield = find("mithril_sq_shield")
    val mortmyremushroom = find("mortmyremushroom")
    val net = find("net")
    val noose_wand = find("noose_wand")
    val pack_airrune = find("pack_airrune")
    val pack_amylase = find("pack_amylase")
    val pack_box_trap = find("pack_box_trap")
    val pack_chaosrune = find("pack_chaosrune")
    val pack_earthrune = find("pack_earthrune")
    val pack_eye_newt = find("pack_eye_newt")
    val pack_feather = find("pack_feather")
    val pack_firerune = find("pack_firerune")
    val pack_mindrune = find("pack_mindrune")
    val pack_ojibway_bird_snare = find("pack_ojibway_bird_snare")
    val pack_vial_empty = find("pack_vial_empty")
    val pack_vial_water = find("pack_vial_water")
    val pack_waterrune = find("pack_waterrune")
    val pestle_and_mortar = find("pestle_and_mortar")
    val piedish = find("piedish")
    val poisonivy_berries = find("poisonivy_berries")
    val pot_flour = find("pot_flour")
    val raw_anchovies = find("raw_anchovies")
    val raw_bass = find("raw_bass")
    val raw_beef = find("raw_beef")
    val raw_chicken = find("raw_chicken")
    val raw_cod = find("raw_cod")
    val raw_lobster = find("raw_lobster")
    val raw_mackerel = find("raw_mackerel")
    val raw_pike = find("raw_pike")
    val raw_salmon = find("raw_salmon")
    val raw_sardine = find("raw_sardine")
    val raw_shark = find("raw_shark")
    val raw_shrimp = find("raw_shrimp")
    val raw_swordfish = find("raw_swordfish")
    val raw_trout = find("raw_trout")
    val raw_tuna = find("raw_tuna")
    val red_spiders_eggs = find("red_spiders_eggs")
    val redberries = find("redberries")
    val ruby = find("ruby")
    val ruby_necklace = find("ruby_necklace")
    val ruby_ring = find("ruby_ring")
    val rune_arrowheads = find("rune_arrowheads")
    val rune_mace = find("rune_mace")
    val rune_pickaxe = find("rune_pickaxe")
    val sapphire = find("sapphire")
    val sapphire_necklace = find("sapphire_necklace")
    val sapphire_ring = find("sapphire_ring")
    val sickle_mould = find("sickle_mould")
    val snape_grass = find("snape_grass")
    val sote_crystal_dust = find("sote_crystal_dust")
    val steel_2h_sword = find("steel_2h_sword")
    val steel_arrowheads = find("steel_arrowheads")
    val steel_full_helm = find("steel_full_helm")
    val steel_kiteshield = find("steel_kiteshield")
    val steel_mace = find("steel_mace")
    val steel_med_helm = find("steel_med_helm")
    val steel_pickaxe = find("steel_pickaxe")
    val steel_sq_shield = find("steel_sq_shield")
    val strung_diamond_amulet = find("strung_diamond_amulet")
    val strung_emerald_amulet = find("strung_emerald_amulet")
    val strung_gold_amulet = find("strung_gold_amulet")
    val strung_ruby_amulet = find("strung_ruby_amulet")
    val strung_sapphire_amulet = find("strung_sapphire_amulet")
    val studded_chaps = find("studded_chaps")
    val tiara_mould = find("tiara_mould")
    val toads_legs = find("toads_legs")
    val tomato = find("tomato")
    val torch_unlit = find("torch_unlit")
    val unicorn_horn = find("unicorn_horn")
    val unlit_candle = find("unlit_candle")
    val vial_empty = find("vial_empty")
    val vial_water = find("vial_water")
    val white_berries = find("white_berries")
    val wine_of_zamorak = find("wine_of_zamorak")
    val wooden_shield = find("wooden_shield")
    val xbows_silver_bolt_mould = find("xbows_silver_bolt_mould")
    val yew_roots = find("yew_roots")

    // Jack's skillcape counter, in skill order rather than alphabetically, because that is the
    // order the shop is stocked in and the order a player reads a skill list.
    //
    // Untrimmed only. A trimmed cape means a second 99 in OSRS, and every `*_trimmed` type here
    // carries the same single `statreq1` as its untrimmed twin -- so stocking one would sell a
    // trim that the equip check could not gate.
    //
    // Hoods are left out as well. 23 capes plus 23 hoods is 46 lines of stock, and a shop that
    // long is untested ground: `Constants.shop_default_size` is 40, which is what the vanilla
    // shop panel shows, and nothing here has ever asked it to draw more.
    //
    // `skillcape_ranging`, `skillcape_runecrafting` and `skillcape_hunting` are the cache's names
    // for the Ranged, Runecraft and Hunter capes; `skillcape_qp` (quest point), `skillcape_ad`
    // (achievement diary) and `skillcape_max` are deliberately absent, since none of them carries
    // a stat requirement and nothing on this server tracks what they are meant to gate.
    val skillcape_attack = find("skillcape_attack")
    val skillcape_defence = find("skillcape_defence")
    val skillcape_strength = find("skillcape_strength")
    val skillcape_hitpoints = find("skillcape_hitpoints")
    val skillcape_ranging = find("skillcape_ranging")
    val skillcape_prayer = find("skillcape_prayer")
    val skillcape_magic = find("skillcape_magic")
    val skillcape_cooking = find("skillcape_cooking")
    val skillcape_woodcutting = find("skillcape_woodcutting")
    val skillcape_fletching = find("skillcape_fletching")
    val skillcape_fishing = find("skillcape_fishing")
    val skillcape_firemaking = find("skillcape_firemaking")
    val skillcape_crafting = find("skillcape_crafting")
    val skillcape_smithing = find("skillcape_smithing")
    val skillcape_mining = find("skillcape_mining")
    val skillcape_herblore = find("skillcape_herblore")
    val skillcape_agility = find("skillcape_agility")
    val skillcape_thieving = find("skillcape_thieving")
    val skillcape_slayer = find("skillcape_slayer")
    val skillcape_farming = find("skillcape_farming")
    val skillcape_runecrafting = find("skillcape_runecrafting")
    val skillcape_hunting = find("skillcape_hunting")
    val skillcape_construction = find("skillcape_construction")
}
