#!/usr/bin/env python3
"""Generate the clue chest's reward casket tables from the OSRS Wiki.

`dropsline` carries every reward casket's loot as `Drop type = reward` rows
"Dropped from" `Reward casket (<tier>)`, and the wiki states its rarities are
*per roll*. Each tier's rows sum to one roll, so each becomes one weighted
table. How many times a casket rolls is vanilla and lives in `ClueTier`, not in
the data.

Left out, and printed:

    #Entrana rows        the weapon-free table for caskets opened on Entrana
    "Always" rows        scroll cases, large spade, clueless scroll, heavy
                         casket -- trail bookkeeping rather than loot
    Clue scroll (master) nothing implements trails
    no rev-233 obj id    post-rev-233 rewards

Output: content/custom/clue-chest/.../cluechest/caskets.toml, in the same
`[[table]]` shape as the npc tables, keyed by `source` instead of `npc`.

Usage:  python3 tools/drop-tables/caskets.py [--dry-run]
"""

import argparse
import collections
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import generate as g  # noqa: E402

TIERS = ["beginner", "easy", "medium", "hard", "elite"]
OUT = (
    g.REPO
    / "content/custom/clue-chest/src/main/resources"
    / "org/rsmod/content/custom/cluechest/caskets.toml"
)
SKIPPED_ITEMS = {"Clue scroll (master)"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="report only; do not write the file"
    )
    args = parser.parse_args()

    obj_symbols = g.read_symbols(g.SYMBOLS / "obj.sym")
    print("fetching infobox_item ...")
    items = g.bucket("infobox_item", ["page_name", "item_name", "item_id"])
    resolve_obj = g.obj_resolver(items, obj_symbols)

    report = g.Report()
    skipped = collections.Counter()
    entries = []
    for tier in TIERS:
        source = f"Reward casket ({tier})"
        drops = g.bucket("dropsline", ["item_name", "drop_json"], where=("page_name", source))
        rows = []
        for raw in drops:
            blob = json.loads(raw["drop_json"])
            item = str(blob.get("Dropped item"))
            if blob.get("Drop type") != "reward":
                skipped[f"{source}: {item} (drop type {blob.get('Drop type')!r})"] += 1
                continue
            if str(blob.get("Dropped from")).endswith("#Entrana"):
                skipped[f"{source}: Entrana table"] += 1
                continue
            if item in SKIPPED_ITEMS:
                skipped[f"{item} (no trails)"] += 1
                continue
            rate = g.parse_rarity(blob.get("Rarity"))
            if rate is None:
                skipped[f"{source}: {item} (unparsed rarity {blob.get('Rarity')!r})"] += 1
                continue
            if rate == "always":
                skipped[f"{source}: {item} (always; trail bookkeeping)"] += 1
                continue
            blob["_page"] = raw.get("item_name")
            obj = resolve_obj(blob)
            if obj is None:
                skipped[f"{source}: {item} (no rev-233 obj)"] += 1
                continue
            low, high = g.parse_quantity(blob)
            rows.append(
                {
                    "obj": obj,
                    "rate": rate,
                    "rarity": str(blob.get("Rarity")),
                    "low": low,
                    "high": high,
                    "noted": g.is_noted(blob),
                    "source": source,
                }
            )

        table, failure = g.build_table(rows, report)
        if table is None:
            raise SystemExit(f"{source}: {failure}")
        total = sum(row["rate"] for row in rows)
        print(
            f"{source}: {len(rows)} rows, per-roll rate sum {total:.4f}, "
            f"out_of {table['out_of']}, {len(table['tertiary'])} spilled to tertiary"
        )
        entries.append({"npc": [], "source": source, "table": table})

    for reason, count in sorted(skipped.items()):
        print(f"  skipped {count:3d}  {reason}")
    for source, obj, rarity, error in report.rounded:
        print(f"  rounded  {source}: {obj} at {rarity} is off by {error:.1%}")

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return
    header = (
        "# Generated by tools/drop-tables/caskets.py from the OSRS Wiki. Do not edit by hand.\n"
        "# One roll of each reward casket; how many rolls a casket gets lives in ClueTier.\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + "\n" + "\n\n".join(g.render_table(e) for e in entries) + "\n")
    print(f"\nwrote {OUT.relative_to(g.REPO)}")


if __name__ == "__main__":
    main()
