package org.rsmod.content.skills.farming.configs

import org.rsmod.api.type.refs.obj.ObjReferences

/**
 * Every seed and sapling that can go into a patch, and everything a patch gives back.
 *
 * The names are the cache's own. Tree patches take a *sapling* (`plantpot_*_sapling`), which is
 * grown from the seed in a filled plant pot; see `SaplingScript`.
 */
object FarmingSeeds : ObjReferences() {
    val asgarnian_hop_seed = find("asgarnian_hop_seed")
    val attas_seed = find("attas_seed")
    val avantoe_seed = find("avantoe_seed")
    val barley_seed = find("barley_seed")
    val belladonna_seed = find("belladonna_seed")
    val cabbage_seed = find("cabbage_seed")
    val cactus_seed = find("cactus_seed")
    val cadantine_seed = find("cadantine_seed")
    val cadavaberry_bush_seed = find("cadavaberry_bush_seed")
    val dwarf_weed_seed = find("dwarf_weed_seed")
    val dwellberry_bush_seed = find("dwellberry_bush_seed")
    val grape_seed = find("grape_seed")
    val guam_seed = find("guam_seed")
    val hammerstone_hop_seed = find("hammerstone_hop_seed")
    val harralander_seed = find("harralander_seed")
    val hespori_seed = find("hespori_seed")
    val huasca_seed = find("huasca_seed")
    val iasor_seed = find("iasor_seed")
    val irit_seed = find("irit_seed")
    val jangerberry_bush_seed = find("jangerberry_bush_seed")
    val jute_seed = find("jute_seed")
    val krandorian_hop_seed = find("krandorian_hop_seed")
    val kronos_seed = find("kronos_seed")
    val kwuarm_seed = find("kwuarm_seed")
    val lantadyme_seed = find("lantadyme_seed")
    val limpwurt_seed = find("limpwurt_seed")
    val marigold_seed = find("marigold_seed")
    val marrentill_seed = find("marrentill_seed")
    val mushroom_seed = find("mushroom_seed")
    val nasturtium_seed = find("nasturtium_seed")
    val onion_seed = find("onion_seed")
    val plantpot_apple_sapling = find("plantpot_apple_sapling")
    val plantpot_banana_sapling = find("plantpot_banana_sapling")
    val plantpot_calquat_sapling = find("plantpot_calquat_sapling")
    val plantpot_celastrus_tree_sapling = find("plantpot_celastrus_tree_sapling")
    val plantpot_crystal_tree_sapling = find("plantpot_crystal_tree_sapling")
    val plantpot_curry_sapling = find("plantpot_curry_sapling")
    val plantpot_dragonfruit_sapling = find("plantpot_dragonfruit_sapling")
    val plantpot_magic_tree_sapling = find("plantpot_magic_tree_sapling")
    val plantpot_mahogany_sapling = find("plantpot_mahogany_sapling")
    val plantpot_maple_sapling = find("plantpot_maple_sapling")
    val plantpot_oak_sapling = find("plantpot_oak_sapling")
    val plantpot_orange_sapling = find("plantpot_orange_sapling")
    val plantpot_palm_sapling = find("plantpot_palm_sapling")
    val plantpot_papaya_sapling = find("plantpot_papaya_sapling")
    val plantpot_pineapple_sapling = find("plantpot_pineapple_sapling")
    val plantpot_redwood_tree_sapling = find("plantpot_redwood_tree_sapling")
    val plantpot_spirit_tree_sapling = find("plantpot_spirit_tree_sapling")
    val plantpot_teak_sapling = find("plantpot_teak_sapling")
    val plantpot_willow_sapling = find("plantpot_willow_sapling")
    val plantpot_yew_sapling = find("plantpot_yew_sapling")
    val poisonivy_bush_seed = find("poisonivy_bush_seed")
    val potato_cactus_seed = find("potato_cactus_seed")
    val potato_seed = find("potato_seed")
    val ranarr_seed = find("ranarr_seed")
    val redberry_bush_seed = find("redberry_bush_seed")
    val rosemary_seed = find("rosemary_seed")
    val seaweed_seed = find("seaweed_seed")
    val snapdragon_seed = find("snapdragon_seed")
    val snape_grass_seed = find("snape_grass_seed")
    val strawberry_seed = find("strawberry_seed")
    val sweetcorn_seed = find("sweetcorn_seed")
    val tarromin_seed = find("tarromin_seed")
    val toadflax_seed = find("toadflax_seed")
    val tomato_seed = find("tomato_seed")
    val torstol_seed = find("torstol_seed")
    val watermelon_seed = find("watermelon_seed")
    val white_lily_seed = find("white_lily_seed")
    val whiteberry_bush_seed = find("whiteberry_bush_seed")
    val wildblood_hop_seed = find("wildblood_hop_seed")
    val woad_seed = find("woad_seed")
    val yanillian_hop_seed = find("yanillian_hop_seed")
}

/** What each crop yields. Herbs come out grimy: the cache calls those `unidentified_*`. */
object FarmingProduce : ObjReferences() {
    val asgarnian_hops = find("asgarnian_hops")
    val banana = find("banana")
    val barley = find("barley")
    val bittercap_mushroom = find("bittercap_mushroom")
    val cabbage = find("cabbage")
    val cactus_potato = find("cactus_potato")
    val cactus_spine = find("cactus_spine")
    val cadavaberries = find("cadavaberries")
    val calquat_fruit = find("calquat_fruit")
    val celastrus_wood = find("celastrus_wood")
    val coconut = find("coconut")
    val cooking_apple = find("cooking_apple")
    val curry_leaf = find("curry_leaf")
    val dragonfruit = find("dragonfruit")
    val dwellberries = find("dwellberries")
    val giant_seaweed = find("giant_seaweed")
    val grapes = find("grapes")
    val hammerstone_hops = find("hammerstone_hops")
    val hespori_seed = find("hespori_seed")
    val jangerberries = find("jangerberries")
    val jute_fibre = find("jute_fibre")
    val krandorian_hops = find("krandorian_hops")
    val limpwurt_root = find("limpwurt_root")
    val marigold = find("marigold")
    val nasturtium = find("nasturtium")
    val nightshade = find("nightshade")
    val onion = find("onion")
    val orange = find("orange")
    val papaya = find("papaya")
    val pineapple = find("pineapple")
    val poisonivy_berries = find("poisonivy_berries")
    val potato = find("potato")
    val redberries = find("redberries")
    val rosemary = find("rosemary")
    val snape_grass = find("snape_grass")
    val strawberry = find("strawberry")
    val sweetcorn = find("sweetcorn")
    val tomato = find("tomato")
    val unidentified_avantoe = find("unidentified_avantoe")
    val unidentified_cadantine = find("unidentified_cadantine")
    val unidentified_dwarf_weed = find("unidentified_dwarf_weed")
    val unidentified_guam = find("unidentified_guam")
    val unidentified_harralander = find("unidentified_harralander")
    val unidentified_huasca = find("unidentified_huasca")
    val unidentified_irit = find("unidentified_irit")
    val unidentified_kwuarm = find("unidentified_kwuarm")
    val unidentified_lantadyme = find("unidentified_lantadyme")
    val unidentified_marentill = find("unidentified_marentill")
    val unidentified_ranarr = find("unidentified_ranarr")
    val unidentified_snapdragon = find("unidentified_snapdragon")
    val unidentified_tarromin = find("unidentified_tarromin")
    val unidentified_toadflax = find("unidentified_toadflax")
    val unidentified_torstol = find("unidentified_torstol")
    val watermelon = find("watermelon")
    val white_berries = find("white_berries")
    val whitelilly = find("whitelilly")
    val wildblood_hops = find("wildblood_hops")
    val woadleaf = find("woadleaf")
    val yanillian_hops = find("yanillian_hops")
}
